### ISSUE TITLE
How to address the form from within button handlers?

### ISSUE THREAD

**Issue by wmodes** [ahdinosaur/meteor-alpaca-bootstrap#1]
I appreciate that you've created a meteor package for alpaca. How does it differ from a more standard use of alpaca? Some of the examples from the Alpaca docs aren't working for me with this package.  For instance, this simple example from the Alpaca docs results in a console error:

```
// alpaca options
"options": {
    "buttons": {
        "submit": {
            "click": function() {
                if (this.isValid(true)) {
                    var value = this.getValue();
                }
           }
       }
   }
}
```

This results in 

```
The compiled template: view-formButtonsContainer for view: VIEW_BOOTSTRAP_EDIT_LIST 
    failed to execute: {"message":"renderedForm is not defined"}
The compiled template: view-form for view: VIEW_BOOTSTRAP_EDIT_LIST failed to execute: 
    {"message":"Alpaca caught an error with the default error handler: The compiled template: 
    view-formButtonsContainer for view: VIEW_BOOTSTRAP_EDIT_LIST failed to execute: 
    {\"message\":\"renderedForm is not defined\"}"}
```

Or this variation also from the Alpaca doc also errors ({\"message\":\"renderedForm is not defined\"}"}):

```
if (renderedForm.isValid(true)) {
    value = renderedForm.getValue();
    alert(JSON.stringify(value, null, "  "));
}
```

I'm pretty sure if I weren't a JS neophyte, this would be trivial to fix, but for me it is a stumper.

I'd love to see some examples in the README of some variations of working code using this meteor package so I can adapt it.

**Comment by ahdinosaur** [comment]
heya! :rabbit2:

this package was a fun hack but i've long since abandoned it, sorry about the confusion. i've now made a note in the GitHub description.

**Comment by wmodes** [comment]
After some research, I think it is a problem with Alpaca not your package.
